spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: ${mockwebserver.url}/.well-known/jwks.json
          jwk-set-uri: ${AUTHORIZATION_SERVER}/.well-known/jwks.json
